version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_maple_content_pipeline
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=maple_tutor_2024
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Toronto
      - TZ=America/Toronto
      - N8N_METRICS=true
      - N8N_METRICS_PREFIX=n8n_
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./workflows:/workflows
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge